---
- hosts: all
  become: True
  ignore_errors: 1
  gather_facts: yes
  #become_user: root

  tasks:
      - name: Create a file
        file: 
          path: /tmp/playbookfile
          mode: '0755'
          state: touch
        tags:
           - file  
      - name: Check something
        command: osdlksksfs
        tags:
           - cmd

      - name: Create a directory
        file:
          path: /tmp/dir
          mode: '0700'
          state: directory  
        tags:
           - dir  
      - name: Create group
        group:
          name: security
          state: present
      - name: Create user Shon   
        user:
          comment: Shon Admin
          shell: /bin/bash
          group: security
          name: shon
        when: ansible_os_family == "Iphone" or ansible_procssor_nproc > 2
      - name: Check uptime
        command: uptime
      - name: Check the date
        shell: cat /etc/passwd | grep shon
       